#[path = "./dom.rs"]
pub mod dom;
#[path = "./html.rs"]
pub mod html;
#[path = "./css.rs"]
pub mod css;
#[path = "./style.rs"]
pub mod style;
#[path = "./layout.rs"]
pub mod layout;
#[path = "./painting.rs"]
pub mod painting;